### ISSUE TITLE
Snadné vypůjčení

### ISSUE THREAD

**Issue by paja2** [skaut/Radio-Tym-Lending-System#1]
Vypůjčení na 1 klik.  Pokud drzim CTRL, nebo shift tak vypůjč stejnému člověku co už jí měl. 
Nebo. 
Alternativne pokud je pole komu prázdné tak vypůjč toku kdo už jí měl.
Nebo 
Placeholder předvyplneno.

**Comment by tomtomklima** [comment]
done
